name: suika-switch
on:
  push:
  pull_request:
jobs:
  switch:
    runs-on: "ubuntu-22.04"
    name: switch
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: prepare devkitpro/devkita64
        run: |
          docker pull devkitpro/devkita64
          docker run -d -it --rm -v $(pwd):/project --name devkita64_run devkitpro/devkita64

      - name: build suika
        run: |
          docker exec -i devkita64_run bash -c "cd /project/build/switch && make -j4"

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: suika.nro
          path: build/switch/*.nro
