name: suika-windows-64
on:
  push:
  pull_request:
jobs:
  linux:
    runs-on: "ubuntu-22.04"
    name: windows
    steps:
    #clone suika2
      - uses: actions/checkout@v2
        with:
          repository: ktabata/suika2
          ref: master
    #build-essential
      - name: build
        run: |
          sudo apt update
          sudo apt install -y mingw-w64
          cd build/mingw-64
          ./build-libs.sh
          make
          make install
      - uses: actions/upload-artifact@v2
        with: 
          name: suika-64.exe
          path: suika-64.exe
